language: node_js
node_js:
  - "8"
install:
  - npm install
  - npm run flow:deps
before_script:
  - npm run flow:check
  - npm run flow:coverage
script:
  - npm run flow:build
  - npm run test
after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3b275930db30627b9311
    on_success: always
    on_failure: always
    on_start: never