site_name: Identity Atheneum
theme:
  name: 'material'
  palette:
    primary: 'pink'
    accent: 'lime'
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.tasklist:
      custom_checkbox: true